[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
transfer_hook = "3oMpgzWU1WePdaH9QyNZewpbU2vRX8aA29yoYK2ZYD3h"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
