[toolchain]
solana_version = "3.1.8"

[features]
resolution = true
skip-lint = false

[programs.localnet]
anchor_realloc = "EK1tkUzyhA3M5BP4aVCFBTSpC4mw8WL5XCjXzApEzejv"

[provider]
cluster = "localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "cargo test"

[hooks]
